# Generated by Django 3.2.8 on 2021-10-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Products', '0005_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery',
            new_name='product',
        ),
    ]
