# Generated by Django 3.2.8 on 2021-10-11 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Products', '0006_rename_gallery_gallery_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Uncategory', max_length=55)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apps_Products.product')),
            ],
        ),
    ]
