# Generated by Django 3.2.8 on 2021-10-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Products', '0008_auto_20211011_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cat_image'),
        ),
    ]
