# Generated by Django 3.2.8 on 2021-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Products', '0020_auto_20211022_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
    ]
