# Generated by Django 3.2.8 on 2021-10-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Products', '0022_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='sub_total',
        ),
    ]
